### ISSUE TITLE
Configuration value should be read from environment variable

### ISSUE THREAD

**Issue by shahariaazam** [shaharia-lab/terediX#16]
Directly adding configuration secret in the yaml file can be less secure. In that case, we may think to read the specific configuration secret from env.

One idea:

```yaml
source:
  my_org_s3_bucket_eu:
    type: aws_s3
    configuration:
      access_key: "env(AWS_ACCESS_KEY)"
      secret_key: "env(AWS_SECRET_KEY)"
      session_token: "xxxx"
      region: "x"
      account_id: "xxx"
```

So, we can be able to read `AWS_ACCESS_KEY` from environment variable and re-assign the value to configuration.
