### ISSUE TITLE
Improving relationship builder

### ISSUE THREAD

**Issue by shahariaazam** [shaharia-lab/terediX#34]
Current relationship builder approach is not scalable specially who has so many resources from different sources. In that case defining relationship with `meta_key` and `meta_value` can be so complicated. Because for different types of `meta_value` for the same `meta_key`, relationship criteria should be defined.

**Current config:**

```yaml
relations:
  criteria:
    - name: "file-system-rule1"
      source:
        kind: "FilePath"
        meta_key: "Machine-Host"
        meta_value: "/some/path"
      target:
        kind: "FilePath"
        meta_key: "Root-Directory"
        meta_value: "/some/other-path"
```

**Proposed config:**

```yaml
relations:
  criteria:
    - name: "file-system-rule1"
      source:
        kind: "FilePath"
        meta_key: "Root-Directory"
      target:
        kind: "FileDirectory"
        meta_key: "Root-Directory"
```

So, in this case we don't need to mention value. Also it would be easier to build the relationship on mass resources optimally.

**Building edge/relation**

`match = [ resource1.(kind) + resource1.(meta_key) == resource2.(kind) + resource2.(meta_key) ]`

So for example, if we want to make a relationship between `FilePath` and `FileDirectory`. The query should look like the following.

```sql
WITH r1 AS (SELECT id, metadata.value
            FROM resources
                     JOIN metadata ON resources.id = metadata.resource_id
            WHERE kind = 'FilePath'
              AND metadata.key = 'Root-Directory'),
     r2 AS (SELECT id, metadata.value
            FROM resources
                     JOIN metadata ON resources.id = metadata.resource_id
            WHERE kind = 'FileDirectory'
              AND metadata.key = 'Root-Directory')
SELECT DISTINCT r1.id AS resource_id, r2.id AS related_resource_id
FROM r1
         JOIN r2 ON r1.value = r2.value
ORDER BY resource_id, related_resource_id;
```
